---
Name: external-analytics-reports--settings
---
Milkyway_SS_ExternalAnalytics_Reports_GoogleAnalytics_Report:
  metrics:
    'At a glance':
      - metric: 'ga:users'
        batch: 1
      - metric: 'ga:newUsers'
        batch: 1
      - metric: 'ga:pageviews'
        batch: 1
      - metric: 'ga:bounceRate'
        batch: 1
        options:
          type: 'percentage'
      - metric: 'ga:avgSessionDuration'
        batch: 1
        options:
          type: 'time'
      - metric: 'ga:pageviewsPerSession'
        batch: 1
        options:
          type: 'int'
      - metric: 'ga:avgTimeOnPage'
        batch: 1
        options:
          type: 'time'
      - metric: 'ga:avgPageLoadTime'
        batch: 1
        options:
          type: 'time'
      - metric: 'ga:socialInteractions'
        batch: 1
      - metric: 'ga:socialActivities'
        batch: 2
      - metric: 'ga:avgServerConnectionTime'
        batch: 2
        options:
          type: 'time'
      - metric: 'ga:avgServerResponseTime'
        batch: 2
        options:
          type: 'time'
      - metric: 'ga:exceptions'
        batch: 2
        title: 'Site Exceptions'
      - metric: 'ga:fatalExceptions'
        batch: 2
        title: 'Site Errors'
      - metric: 'ga:organicSearches'
        batch: 2
    'Google Adwords':
      - metric: 'ga:impressions'
        batch: 3
      - metric: 'ga:cpc'
        batch: 3
        title: 'Cost per Click'
        options:
          type: 'money'
      - metric: 'ga:ctr'
        batch: 3
        title: 'Click Through Rating'
        options:
          type: 'percentage'
    'Goals':
      - metric: 'ga:goalStartsAll'
        title: 'No. of Goals'
        batch: 3
      - metric: 'ga:goalConversionRateAll'
        title: 'Goal Conversion Rate'
        batch: 3
        options:
          type: 'percentage'
      - metric: 'ga:goalAbandonRateAll'
        batch: 3
        title: 'Abandonment Rate'
        options:
          type: 'percentage'

  charts:
    traffic:
      title: 'Site Traffic'
      query:
        metrics: 'ga:sessions'
        dimensions: 'ga:date'
      chart:
        type: 'LINE'

    mobile:
      title: 'Mobile Traffic'
      query:
        metrics: 'ga:sessions'
        dimensions: 'ga:mobileDeviceInfo'
        segment: 'gaid::-14'
        'max-results': 5
      chart:
        type: 'PIE'

    weekly:
      title: 'Weekly Traffic'
      query:
        metrics: 'ga:users'
        dimensions: 'ga:dayOfWeekName'
      chart:
        type: 'LINE'

    countries:
      title: 'Users by Country'
      query:
        metrics: 'ga:sessions'
        dimensions: 'ga:country'
        sort: '-ga:sessions'
      chart:
        type: 'GEO'

    browser:
      title: 'Pageviews by Browser'
      query:
        metrics: 'ga:pageviews'
        dimensions: 'ga:browser'
        sort: '-ga:pageviews'
        'max-results': 5
      chart:
        type: 'PIE'

    trafficSources:
      title: 'Traffic Sources'
      query:
        metrics: 'ga:sessions'
        dimensions: 'ga:medium'
        sort: '-ga:sessions'
      chart:
        type: 'PIE'

    topContent:
      title: 'Top Content'
      query:
        metrics: 'ga:pageviews,ga:uniquePageviews,ga:timeOnPage,ga:bounceRate,ga:entrances,ga:exits'
        dimensions: 'ga:pagePath'
        sort: '-ga:pageviews'
        'max-results': 5

    topKeywords:
      title: 'Top Keywords'
      query:
        metrics: 'ga:sessions'
        dimensions: 'ga:keyword'
        sort: '-ga:sessions'
        'max-results': 5

    loyalty:
      title: 'New vs. Returning Visitors'
      query:
        metrics: 'ga:sessions'
        dimensions: 'ga:userType'
      chart:
        type: 'PIE'

    topChannels:
      title: 'Top Channels'
      query:
        metrics: 'ga:sessions'
        dimensions: 'ga:channelGrouping'
        sort: '-ga:sessions'
      chart:
        type: 'PIE'

    visitsViaSocial:
      title: 'Visits via Social Media'
      query:
        metrics: 'ga:sessions'
        dimensions: 'ga:dayOfWeekName'
        filters: 'ga:hasSocialSourceReferral==Yes'
      chart:
        type: 'LINE'

    topReferrers:
      title: 'Top Referrers'
      query:
        metrics: 'ga:users,ga:pageviews,ga:bounceRate'
        dimensions: 'ga:fullReferrer'
        sort: '-ga:users'
        filters: 'ga:medium==referral'
        'max-results': 5